version: '3.8'
services:
  vite-app:
    build: .
    ports:
      # - "5173:5173" # ホストのポート:コンテナのポート（開発サーバー）
      - "4173:4173" # ホストのポート:コンテナのポート（プレビューモード）
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
